### DISCUSSION TITLE
0.24.0

### DISCUSSION THREAD

**Discussion by jonasbn** [rojopolis/spellcheck-github-actions#97] [General]
## 0.24.0, 2022-05-17, feature release, update not required

- @riccardoporreca created issue [#68](https://github.com/rojopolis/spellcheck-github-actions/issues/68) requested the ability to create an output artifact.
  
  With release 0.24.0 this is now available.

  The action configuration has to have the `output_file` parameter specified, which is a new optional parameter.

  ```yaml
  name: Spellcheck Action
  
  on:
    workflow_dispatch:
    push:
  
  jobs:
    build:
      name: Spellcheck
      runs-on: ubuntu-latest
      steps:
  
      - uses: actions/checkout@v3
  
      - uses: rojopolis/spellcheck-github-actions@0.24.0
        name: Spellcheck (no output file)
        with:
          source_files: README.md CHANGELOG.md
  
      - uses: rojopolis/spellcheck-github-actions@0.24.0
        name: Spellcheck (with output file)
        with:
          source_files: README.md CHANGELOG.md
          task_name: Markdown
          output_file: spellcheck-output.txt
  
      - uses: actions/upload-artifact@v3
        name: Archive spellcheck output output
        with:
          name: Spellcheck artifact
          path: spellcheck-output.txt
  ```

  This introduces the use of the `upload-artifact@v3` action.

  The generated artifact can be downloaded via GitHub UI/API, please consult the documentation for details and pointers.

  Thanks to @riccardoporreca for his suggestion.

<hr /><em>This discussion was created from the release <a href='https://github.com/rojopolis/spellcheck-github-actions/releases/tag/0.24.0'>0.24.0</a>.</em>
