### DISCUSSION TITLE
Ignore code blocks in markdown

### DISCUSSION THREAD

**Discussion by arivictor** [rojopolis/spellcheck-github-actions#99] [General]
Hi,

I'm looking to use your action in my pipeline. I'm running it over my markdown docs, its catching spelling mistakes very well but its also picking up issues in the example code blocks in the markdown files. To reduce the noise, is it possible to ignore the code blocks?

My config:

```
matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.md'
  default_encoding: utf-8
```

I'm looking at the example configs from PySpell and it has this:

```
matrix:
- name: python
  sources:
  - pyspelling/**/*.py
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.python:
      strings: false
      comments: false
```

Is there a similar boolean toggle for markdown to ignore code blocks?

Ty!

**Comment by facelessuser** [comment]
I'm the author of the underlying library that performs the spell checking. The Markdown "filter" simply converts the Markdown content into HTMl. The best way to avoid code blocks is to use the HTML filter right after and exclude code blocks.

Example: https://github.com/facelessuser/pyspelling/blob/master/.pyspelling.yml#L77

**Comment by jonasbn** [comment]
Hi @arivictor

Good question, I will update the documentation for the action, based on the resource from @facelessuser so it is more clear.

**Comment by chester-leung** [comment]
Hi, I am running into a similar issue where the spellchecker is erroring on text within a code block. For example, I have the following code block in my markdown file:

```
# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Update homebrew
brew update
brew doctor # fix any issues found here

# Install node v16 -- read homebrew's output for further configuration
brew install node@16

# Install yarn
npm install --global yarn
```

And the action outputs the following:

```
Misspelled words:
<htmlcontent> docs/platform/frontend/install.md: html>body>ol>li>p
--------------------------------------------------------------------------------
fsSL
githubusercontent
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> docs/platform/frontend/install.md: html>body>ol>li>h1
--------------------------------------------------------------------------------
homebrew's
--------------------------------------------------------------------------------
```

As such, I don't expect an error for `fsSL` and `githubusercontent`

My `.spellcheck.yml` looks like this:

```
---
matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - docs/spelling_wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
            - code
            - pre
    sources:
      - 'docs/**/*.md'
    default_encoding: utf-8
```

Any ideas what I'm doing wrong?

**Reply by facelessuser** [reply]
I can't tell from your example, but is your code block a fenced code block? If so, Python Markdown, by default, follows the original Markdown spec, which did not include fenced code, so you need to use a fenced code extension. There is https://facelessuser.github.io/pymdown-extensions/extensions/superfences/ and the built-in Python Markdown one called https://python-markdown.github.io/extensions/fenced_code_blocks/.

**Reply by chester-leung** [reply]
Hi @facelessuser thanks for your reply. It is indeed a fenced code block. By "use a fenced code extension" do you mean install the corresponding package? I tried pip installing the `markdown` package before running this spellcheck action, but am running into the same issue.

**Comment by jonasbn** [comment]
Hi @chester-leung 

I have played around with your example and it seems to have issues with the Markdown.

- `#` breaks the fence
- multiple lines break the fence

This example gets ignored (works):

````
   ```shell
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   ```
````

This does not:

````
   ```shell
   # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   ```
````

And this does not, I removed the `#`, but it still failed

````
    ```shell
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    brew update
    brew doctor 

    brew install node@16

    npm install --global yarn
    ```
````

@facelessuser it there something, which have to be specified additionally in the configuration to get the fences to be respected.

All of the above examples where tested embedded in a Markdown file, using the above configuration.

**Reply by facelessuser** [reply]
Yes, as I said, a fenced code extension is needed as fenced code is not part of the original Markdown spec, even if it is more ubiquitous now.

An example of enabling fenced code is here: https://github.com/facelessuser/coloraide/blob/main/.pyspelling.yml#L40. It uses SuperFences which I am also the author of.

If you don't use a fenced code extension, it will only do inline code blocks, and that is probably why `# header` breaks it.

**Reply by jonasbn** [reply]
Hi @facelessuser 

Works like a charm, with the following configuration.

```yaml
---
matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - docs/spelling_wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
          - pymdownx.superfences
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
          - code
          - pre
    sources:
      - 'docs/**/*.md'
    default_encoding: utf-8
```

I will update the documentation.
