### ISSUE TITLE
Clarify how Ignore code blocks in Markdown

### ISSUE THREAD

**Issue by jonasbn** [rojopolis/spellcheck-github-actions#100]
### Discussed in https://github.com/rojopolis/spellcheck-github-actions/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **arivictor** June  8, 2022</sup>
Hi,

I'm looking to use your action in my pipeline. I'm running it over my markdown docs, its catching spelling mistakes very well but its also picking up issues in the example code blocks in the markdown files. To reduce the noise, is it possible to ignore the code blocks?

My config:

```
matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.md'
  default_encoding: utf-8
```

I'm looking at the example configs from PySpell and it has this:

```
matrix:
- name: python
  sources:
  - pyspelling/**/*.py
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.python:
      strings: false
      comments: false
```

Is there a similar boolean toggle for markdown to ignore code blocks?

Ty!</div>
