### ISSUE TITLE
 Spelling check failed but GitHub Action succeed

### ISSUE THREAD

**Issue by nlhomme** [rojopolis/spellcheck-github-actions#166]
Hello,

This is my configuration inside the folder `.github/workflows`:

![image](https://github.com/igsekor/pyspelling-any/assets/9362475/1c345309-e440-4cd3-89eb-edb9cf162457)

.spelling_action.yml
```
name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      with:
        config_path: .github/workflows/.spellcheck.yml
        output_file: spellcheck-output.txt
```

.spellcheck.yml
```
matrix:
- name: Markdown
  aspell:
    lang: fr
    d: fr_FR
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/workflows/.wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '_posts/*.md'
  default_encoding: utf-8
```

.wordlist.txt
```
CD-ROM
```

When I run a GitHub Action, the logs says that spell check has failed:
```
(...)
Misspelled words:
<htmlcontent> _posts/2023-07-04-Bujur-le-monde.md: html>body>p
--------------------------------------------------------------------------------
LHOMME
Nicolas
height
width
--------------------------------------------------------------------------------


!!!Spelling check failed!!!
``` 

But in the end, the action is marked as a success
![image](https://github.com/igsekor/pyspelling-any/assets/9362475/e72e734d-5a5d-47d7-965e-8ddfe4a05163)

Can you help me find what's wrong?

Regards
