### ISSUE TITLE
Verification Scope Restriction

### ISSUE THREAD

**Issue by daelynum** [rojopolis/spellcheck-github-actions#173]
The spelling verification reviews all repository files, wasting time on unchanged files. Is it possible to limit checks to files in a specific pull request, focusing only on new or modified content?

Adding a "changed_only: true" flag could be a viable solution to this issue.

**Comment by jonasbn** [comment]
Hi @daelynum 

This sound like a good suggestion, I will dig into a possible solution.

**Comment by jonasbn** [comment]
Hi @daelynum 

I have attempted with a configuration using the action: 

- https://github.com/marketplace/actions/changed-files

This is the example/proof of concept and it seems to be working, it might require some tweaks and it will require some additional documentation updates.

```yaml
name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: tj-actions/changed-files@v39
      id: changed_files

    - name: Run Spellcheck
      id: spellcheck
      uses: rojopolis/spellcheck-github-actions@0.34.0
      with:
        task_name: Markdown
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}
        output_file: spellcheck-output.txt

    - uses: actions/upload-artifact@v3
      if: '!cancelled()'
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt
```

REF: https://github.com/jonasbn/til/blob/master/.github/workflows/spellcheck.yml

Let me know what think.
