### ISSUE TITLE
Support ignoring files

### ISSUE THREAD

**Issue by martincostello** [rojopolis/spellcheck-github-actions#176]
From looking at the documentation, it looks like you can specify files to check, but you can't specify files to exclude.

I have dozens of files I do want to check, but only a handful I want to ignore.

With [DavidAnson/markdownlint-cli2-action](https://github.com/DavidAnson/markdownlint-cli2-action) for example, I can specify some globs:

```yaml
- name: Lint Markdown files
  uses: DavidAnson/markdownlint-cli2-action@v13
  with:
    globs: |
      **/*.md
      !CHANGELOG.md
      !**/BenchmarkDotNet.Artifacts/**/*.md
```

It would be nice if similar functionality were supported so I don't need to list every file individually in the case I want to only ignore one or more files.

**Comment by jonasbn** [comment]
Hi @martincostello 

The action is just a utility for PySpelling, so you could look into it's configuration, especially [the part](https://facelessuser.github.io/pyspelling/configuration/#sources) on `sources`.

I am doing some basic ignoring in one of my own repositories.

```yaml
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '!_site/*.md|!osx/list_available_voices_for_speechsynthesis.md|!clang/diagnostic_flags.md|*/*.md|README.md'
  default_encoding: utf-8
```

REF: https://github.com/jonasbn/til/blob/master/.spellcheck.yaml

I am no wizard on PySpelling and: [wcmatch.glob](https://facelessuser.github.io/wcmatch/glob/) which is the component used, perhaps it can help you out. 

I will leave this issue open and will await you feedback.
