### ISSUE TITLE
Make pre-commit hook out of this repository

### ISSUE THREAD

**Issue by Lasica** [rojopolis/spellcheck-github-actions#188]
Hello, I've had a need to add spellchecking to my repo docs. For this purpose I've created my hook definition based on this repository. I think that's probably a small addition that would be welcome and more fitting in this repository directly.

All it takes is properly defined `pre-commit-hooks.yml` file. Here is sample of what my looks like:

```yaml
-   id: pyspelling-docker
    name: Pyspelling in docker
    description: Pyspelling with aspell using Dockerfile of github action, based on https://github.com/rojopolis/spellcheck-github-actions
    language: docker_image
    entry: jonasbn/github-action-spellcheck:latest
```

with readme description of how to configure it:

Define in `.pre-commit-config.yaml`:

```yaml
- repo: https://github.com/getindata/py-pre-commit-hooks
  rev: v0.1.3
  hooks:
  - id: pyspelling-docker
```

What do you think? Do you want PR for this?
