### ISSUE TITLE
issue running spellcheck action

### ISSUE THREAD

**Issue by shahzebsiddiqui** [rojopolis/spellcheck-github-actions#2]
![image](https://user-images.githubusercontent.com/12942230/72447500-6e5c2f00-3783-11ea-911b-c7bb97ecd06e.png)

My spellchecker action is the following:

```
  
name: Spell Checker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.2.0
```

I tried to do spellcheck on push and pr and it failed.  This build can be found at https://github.com/HPC-buildtest/buildtest-framework/commit/9ae66e412c0545977d08c15d0952f62b91d253ee/checks?check_suite_id=402308725

It is looking for a `/wordlist` file which is not found
