### ISSUE TITLE
Ignoring paths is not supported in source_files

### ISSUE THREAD

**Issue by carusooo** [rojopolis/spellcheck-github-actions#213]
I'm having issues with configuring spellcheck to ignore file paths when passed in via the source_files argument

From the documentation here and in PySpelling, it looks like this should be all that's required.

```yaml
  sources:
  - '**/*.md*|!docs/api/**'`
 ```
This is how the action is invoked

```yaml
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.0
      name: Checkout
    - id: changed_files
      name: Changed Files
      uses: tj-actions/changed-files@v45
      with:
        files: |
           **.mdx
    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
        echo "$file was changed"
        done
    - uses: rojopolis/spellcheck-github-actions@0.41.0
      name: Spellcheck
      
      if: ${{ steps.changed_files.outputs.all_changed_files }}
      with:
        config_path: spellcheck.yaml
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}
        task_name: Markdown
```

I suspect this is working as intended, wanted to confirm. I think I'll need to filter out the changed files in the github action
