### ISSUE TITLE
SpellCheck Skipping Mardkown Files

### ISSUE THREAD

**Issue by sharadregoti** [rojopolis/spellcheck-github-actions#231]
My Github action
```
name: Spellcheck

on:
  pull_request:
    paths:
      - '**/*.md'  # Trigger only if Markdown files change

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all changed markdown files
        uses: tj-actions/changed-files@v45
        id: changed_files
        with:
          files: |
            **.md
            
      - name: Run Spellcheck
        id: spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          task_name: Markdown
          source_files: ${{ steps.changed_files.outputs.all_changed_files }}
```

My `.spellcheck.yaml` at the root of the repository
```
matrix:
  - name: Markdown
    aspell:
      aspell:
        lang: en
        d: en_US # American English
    dictionary:
      wordlists:
        - .wordlist.txt  # Custom keywords to ignore
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    default_encoding: utf-8
```

When the GA runs, the CI always passes. The following are the logs from CI:
```
Using pyspelling on configuration outlined in >.spellcheck.yaml<
Source files to check: >docs/content/environment-variables.md<
Running task >Markdown<
Skipping file >docs/content/environment-variables.md<
Checking files specification in sources_list as: ><
No files to check, exiting
```

If you remove `source_files` from GA and add the `source` field in the spellcheck.yaml with `docs/content/environment-variables.md`, it works and shows errors. I am not sure what is wrong with my dynamic configuration.

**Comment by jonasbn** [comment]
Hi @sharadregoti 

I will have a look at your description, your repository is not public by any chance?

**Comment by jonasbn** [comment]
Hi @sharadregoti 

It looks as if your `.spellcheck.yaml` is missing the `sources` part.

From the [PySpelling configuration documentation](https://facelessuser.github.io/pyspelling/configuration/#sources)

> Each spelling task must define a list of sources to search via the sources key. Each source should be a glob pattern that should match one or more files. PySpelling will perform a search with these patterns to determine which files should be spell checked.

This is my revised, but untested suggestion to how your configuration should look:

```yaml
matrix:
  - name: Markdown
    aspell:
      aspell:
        lang: en
        d: en_US # American English
    dictionary:
      wordlists:
        - .wordlist.txt  # Custom keywords to ignore
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    default_encoding: utf-8
    sources:
    - '**/*.md'
```
