### ISSUE TITLE
Ignore spell check in hyperlinks

### ISSUE THREAD

**Issue by MarekLani** [rojopolis/spellcheck-github-actions#24]
Please is there a way how to ignore spell check of hyperlinks? 
[link text](this_should_be_ignored)

**Comment by jonasbn** [comment]
Meaning you want to check the spelling of the "link text", but not the actual URL?

**Comment by jonasbn** [comment]
Hi @MarekLani 

I did a test, running `pyspelling` manually on a HTML file, this does not report any spelling errors for the HTML part, only the text part.

```bash
$ clear; pyspelling --config spellcheck.yaml
Misspelled words:
<htmlcontent> index.html: html>body
--------------------------------------------------------------------------------
baader
evin
speeling
--------------------------------------------------------------------------------

!!!Spelling check failed!!!
```

HTML file:

```html
<a href="/baad_speling/">evin baader speeling</a>
```

Using the configuration outlined here:

```yaml
matrix:
- name: HTML
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
    comments: false
  sources:
  - '**/*.html'
  default_encoding: utf-8
```

Could you please provide me with a copy of you configuration file?

**Comment by MarekLani** [comment]
@jonasbn thank you for response and sorry I should have stated, that this is present in md check. I meant following:
`[Link text to be checked](link_address_should_not_be_checked)`

This is my config:

```
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - wordlist.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
    - pyspelling.filters.html:
        comments: true
        attributes:
        - title
        - alt
        ignores:
        - ':matches(code, pre)'
        - 'code'
        - 'pre'
  sources:
  - '**/*.md'
  default_encoding: utf-8
```
