### ISSUE TITLE
Exclude directory from spell checker

### ISSUE THREAD

**Issue by strongishllama** [rojopolis/spellcheck-github-actions#26]
It would be great if we could exclude a directory from the spell checker. I've tried using the PySpelling [configuration](https://facelessuser.github.io/pyspelling/configuration/) to do this, but it doesn't seem to work.

Thanks!

**Comment by facelessuser** [comment]
What have you tried? I'm the author of pyspelling, and that is usually the way to exclude directories.

**Comment by strongishllama** [comment]
This is what my .spellcheck.yml file looks like. I'm trying to ignore the assets directory.
```yml
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  sources:
  - '**/*.md|!assets/*'
  default_encoding: utf-8
```
