### ISSUE TITLE
Error: Unable to find or load pyspelling configuration from spellcheck.yaml

### ISSUE THREAD

**Issue by Maniacxxx** [rojopolis/spellcheck-github-actions#37]
![image](https://user-images.githubusercontent.com/52683414/108392803-0b886300-71e1-11eb-95bf-6d9b3c667425.png)

**Comment by jonasbn** [comment]
Hi @Maniacxxx 

Can you post your `spellcheck.yaml` and link to repository if it is public

**Comment by jonasbn** [comment]
Hi @Maniacxxx 

The error indicated by your screenshot points to an already documented diagnostic.

### Diagnostic text: `ValueError: Unable to find or load pyspelling configuration from`

This diagnostic indicates that the configuration file pointed to with the `--config` (`-c`) parameter cannot be located.

1. Check that a file with the indicated name exists.

`ValueError: Unable to find or load pyspelling configuration from spellcheck.yaml`

Indicates: `spellcheck.yaml` so this file should exist in the repository.

If the file is available in the repository, please check that your workflow is configured correctly, with the following line, which enables the action Checkout.

`uses: actions/checkout@master`

In full context:

```yaml
name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/0.11.0
      name: Spellcheck
```

I am closing this issue, please reopen the issue is not solved by the steps listed above.
